### ISSUE TITLE
Not showing up on UI

### ISSUE THREAD

**Issue by TheTechNeverEnds** [gefs-plugins/flight-management-computer#6]
I recently just downloaded the plugin through TamperMonkey and I was excited to use the plugin but I didn't see any FMC button or shortcut anywhere. Please Help. And if you could also include a manual for it just in case. Thank You.

**Comment by hAr1x** [comment]
This version of FMC is no longer supported. Please see [the new version](https://github.com/gefs-plugins/fmc-requirejs).
